export { default as Tag } from "./Tag/Tag";
export { default as Map } from "./Map/Map";
export { default as Title } from "./Title/Title";
export { default as Button } from "./Button/Button";
export { default as Header } from "./Header/Header";
export { default as Subject } from "src/routes/TouristRoutes/TouristRoute/Subject/Subject";
export { default as ImageSlider } from "./ImageSlider/ImageSlider";
export { default as TouristRoute } from "src/routes/TouristRoutes/TouristRoute/TouristRoute";
export { default as ChangedBlock } from "./ChangedBlock/ChangedBlock";
